### ISSUE TITLE
`OwningHandle::new` should allow handle to propagate errors.

### ISSUE THREAD

**Issue by jonhoo** [Kimundi/owning-ref-rs#19]
If the operation creating the handle fails for some reason, exposing that error is currently quite difficult. Could the signature of `new` perhaps be changed to
```rust
fn new<F, E>(o: O, f: F) -> Result<Self, E>
  where F: Fn(*const O::Target) -> Result<H, E> {}
```

**Comment by Kimundi** [comment]
Sounds reasonable! Instead of changing new, I added an `try_new()` constructor though. 

Check it out on master and tell me if its the expected semantic. :)

**Comment by jonhoo** [comment]
`try_new` seems perfect!
