### ISSUE TITLE
Enhancement: hold things that reference the owner

### ISSUE THREAD

**Issue by jethrogb** [Kimundi/owning-ref-rs#2]
I think the functionality of this crate could be extended to hold an owner as well as something that has a lifetime less than or equal to the owner, in a manner similar to the `map` function. This would help getting rid of lifetime parameters that are carried all the way up through many structures.

For example, say I have an `ArcRef<Mutex<T>>`. I'd like to store a `MutexGuard<'a,T>` along-side it. This is safe as long as I know `ArcRef<Mutex<T>>: 'a`. I currently have [an implementation that's not based on OwningRef](https://github.com/jethrogb/namedlock-rs/blob/master/src/arcmutexguard.rs) which I intend to port to OwningRef.

**Comment by shepmaster** [comment]
I *think* I was looking for the same thing. A slimmed-down example of something I might like to have:

```rust
extern crate owning_ref;

use std::collections::HashSet;
use owning_ref::OwningRef;

fn main() {
    let or = OwningRef::new(Box::new(42));
    or.map(|answer| {
        let mut set = HashSet::new();
        set.insert(answer);
        set
    });
}
```

@Kimundi, do you feel like something like this is possible? I'd be happy to contribute some code if you could give some vague hand-wavy direction to start in. :smile_cat:

**Comment by Kimundi** [comment]
I don't think its possible due to language reasons right now - if you find a way to actually implement it, then by all means make a PR. :)

**Comment by diwic** [comment]
The [https://github.com/diwic/refstruct-rs](refstruct) crate is some research on how to create something related to this issue. Might be useful?

**Comment by dippi** [comment]
Uhm, I patched together a possible solution. It should do exactly what `OwningRef` can, plus should support any struct that generically depends on the owned data (like `Box<T>`+`Option<&T>`, `Vec`+`Iter`, `Box<Mutex>`+`MutexLock`, `MutexLock<T>`+`&mut T`) and, as you can see from the example, it's also nestable.
Do you think it makes sense and it is worth developing? Does it look safe or do you spot any danger?
```rust
use std::marker::PhantomData;
use std::ops::Deref;
use std::sync::Mutex;

struct OwnedDep<'a, O: 'a, T: 'a> {
    phantom: PhantomData<&'a O>,
    owned: O,
    dep: T,
}

impl<'a, O, T: ?Sized> OwnedDep<'a, O, &'a T>
    where O: Deref<Target = T>
{
    fn new(it: O) -> Self {
        let a = &*it as *const _;
        OwnedDep {
            phantom: Default::default(),
            owned: it,
            dep: unsafe { &*a },
        }
    }
}

impl<'a, O, T> OwnedDep<'a, O, T> {
    fn map<'b, F, U: 'b>(self, f: F) -> OwnedDep<'b, O, U>
        where 'a: 'b,
              F: FnOnce(T) -> U
    {
        OwnedDep {
            phantom: Default::default(),
            owned: self.owned,
            dep: f(self.dep),
        }
    }
}

fn main() {
    let a = OwnedDep::new(Box::new(Mutex::new(1)));
    let a = a.map(|it| it.lock().unwrap());
    let a = a.map(|it| OwnedDep::new(it));
    println!("{:?} {:?}", a.owned, a.dep.dep);
}
```

Note: at the moment It's just a draft and lacks of the `StableAddress` safety mesures and all the goodies, but it should be reasonably clear.

**Comment by Kimundi** [comment]
If I haven't entirely misunderstood, then `OwningHandle` fills this need now. Closing.

**Comment by jethrogb** [comment]
Neat, thanks!
