### ISSUE TITLE
Publish new version on crates.io

### ISSUE THREAD

**Issue by fitzgen** [Kimundi/owning-ref-rs#20]
Hello, I'd like to use `OwningHandle` in a library that I am publishing on crates.io, but because it is only available on tip, I can't effectively start using it until there is an `owning_ref` on crates.io with `OwningHandle`.

Thank you very much for your time!

**Comment by Kimundi** [comment]
Hi, sorry about that. Seems that I forgot to publish a new version after the merge, and then was busy enough over the holiday season to not notice the github notifications.

I just published a new version to crates.io
