### ISSUE TITLE
Why does OwningHandle::new take Fn?

### ISSUE THREAD

**Issue by Storyyeller** [Kimundi/owning-ref-rs#23]
Why does OwningHandle::new take Fn? As far as I can tell, it should only require FnOnce. Not that it matters much in this case, but it's nice to be as flexible as possible.

**Comment by Kimundi** [comment]
Hi, I'm [sincerely sorry for taking so long to respond.](https://gist.github.com/Kimundi/9b10629d29adbf163d8eb053ddaa1f38)

Good point though, I think that just slipped by in the original PR. Fixing it right now.
