### ISSUE TITLE
merge FixedDeref and StableAddress

### ISSUE THREAD

**Issue by Storyyeller** [Kimundi/owning-ref-rs#25]
This crate is very similar to the rental crate. In particular, they both define an unsafe trait to represent types which point to a fixed address (FixedDeref for rental and StableAddress for owning_ref). I think it would make sense to place this trait in a separate crate that you both depend on. This reduces code duplication and makes it easier for library authors to interact with these crates. For example, if I define a custom Rc type, I'd need to implement one trait to make it interoperable with rental and another for owning_ref. Putting StableAddress in a seperate crate will make things much nicer.

For reference, here are the impls of FixedDeref and StableAddress. The only difference is that StableAddress isn't impled for references, which is probably an oversight.

```rust
unsafe impl<'t, T: ?Sized> FixedDeref for &'t T { }
unsafe impl<'t, T: ?Sized> FixedDeref for &'t mut T { }

unsafe impl<T: ?Sized> FixedDeref for Box<T> { }
unsafe impl<T> FixedDeref for Vec<T> { }
unsafe impl FixedDeref for String { }

unsafe impl<T: ?Sized> FixedDeref for rc::Rc<T> { }
unsafe impl<T: ?Sized> FixedDeref for sync::Arc<T> { }

unsafe impl<'t, T: ?Sized> FixedDeref for cell::Ref<'t, T> { }
unsafe impl<'t, T: ?Sized> FixedDeref for cell::RefMut<'t, T> { }
unsafe impl<'t, T: ?Sized> FixedDeref for sync::MutexGuard<'t, T> { }
unsafe impl<'t, T: ?Sized> FixedDeref for sync::RwLockReadGuard<'t, T> { }
unsafe impl<'t, T: ?Sized> FixedDeref for sync::RwLockWriteGuard<'t, T> { }
```

```rust
unsafe impl<T: ?Sized> StableAddress for Box<T> {}
unsafe impl<T> StableAddress for Vec<T> {}
unsafe impl StableAddress for String {}

unsafe impl<T: ?Sized> StableAddress for Rc<T> {}
unsafe impl<T: ?Sized> CloneStableAddress for Rc<T> {}
unsafe impl<T: ?Sized> StableAddress for Arc<T> {}
unsafe impl<T: ?Sized> CloneStableAddress for Arc<T> {}

unsafe impl<'a, T: ?Sized> StableAddress for Ref<'a, T> {}
unsafe impl<'a, T: ?Sized> StableAddress for RefMut<'a, T> {}
unsafe impl<'a, T: ?Sized> StableAddress for MutexGuard<'a, T> {}
unsafe impl<'a, T: ?Sized> StableAddress for RwLockReadGuard<'a, T> {}
unsafe impl<'a, T: ?Sized> StableAddress for RwLockWriteGuard<'a, T> {}
```

**Comment by Storyyeller** [comment]
P.S. CloneStableAddress should be impled for Ref as well.

**Comment by Kimundi** [comment]
Hi, I'm [sincerely sorry for taking so long to respond.](https://gist.github.com/Kimundi/9b10629d29adbf163d8eb053ddaa1f38)

I fully agree with your proposal. This crate is in need of a refactor anyway, so factoring out the `StableAddress` trait seems like a good first step.

**Comment by Storyyeller** [comment]
Here's the draft version of the new crate: https://github.com/Storyyeller/stable_address_trait/blob/master/src/lib.rs

The only change code wise is that I added impls for &T and &mut T. Apart from that, I wrote a bunch of documentation describing the requirements of the trait. You should check over that and make sure it is correct.

If you think it's ok, I'll go ahead and publish it on crates.io and then send a PR to update owning_ref to use it.

**Comment by Kimundi** [comment]
The code looks good, and the rename to `StableDeref` seems also fine.

I think the docs could use a few rewordings though:

- "immutable reference/borrow" -> "shared reference/borrow"
- The explanation about the guarantees trait implementers need to uphold seem a bit confusing/vague for the parts where `DerefMut` comes into play. When I read through it just now I was not sure from the description how `&mut Self` methods that can cause address changes affect the reasoning. So, I think you should a section or rewording like "&Self methods are allowed and must not change the address, but &mut Self are unspecified, thus might change the address and should thus generally not be called in combination with this trait."
