### ISSUE TITLE
Two mut Refs at the same time

### ISSUE THREAD

**Issue by chpio** [Kimundi/owning-ref-rs#48]
`as_owner_mut` creates an additional mut ref to the stored ref, so we end up having two mutable ref ***at the same time***. Why is this allowed? Changing data thru the mut ref should at least invalidate the stored ref (which is achievable by using the `into_owned` method -> mutating the owner -> making an *OwningRefMut* and mapping it again).

<http://kimundi.github.io/owning-ref-rs/owning_ref/struct.OwningRefMut.html#method.as_owner_mut>

**Comment by chpio** [comment]
@Storyyeller Yeah? I was saying that it should be used instead of `as_owner_mut`.

**Comment by Storyyeller** [comment]
I thought you were saying that you had found a soundness hole. Have you?

**Comment by chpio** [comment]
https://github.com/chpio/owning_ref_test/blob/master/src/main.rs

**Comment by chpio** [comment]
\*bump\*

i guess a simple fix would be to remove *as_owner_mut*?
