### ISSUE TITLE
Add `and_then`?

### ISSUE THREAD

**Issue by dpc** [Kimundi/owning-ref-rs#5]
It would be useful to have:

```rust
fn and_then<F, U: ?Sized>(self, f: F) -> Option<OwningRef<O, U>> where O: StableAddress, F: FnOnce(&T) -> Option<&U>
```

Sometimes, the converstion in `f` can be conditional and sometimes yeild no results. Example would be `Any::downcast_ref()`, that I'm using here:

https://github.com/dpc/mioco/pull/130/files#diff-08f34ae8c4d103993320447b5f4f1fcdR507

Because I have no better way to do it, I have to first check if the operation will fail or not, and then repeat it if needed.

**Comment by Kimundi** [comment]
I added a `try_map()` function that works with a `Result` that should solve this case.

**Comment by Kimundi** [comment]
Got a thumbs up, so I assume this is solved. :)
