### ISSUE TITLE
Erasing the Box itself

### ISSUE THREAD

**Issue by diwic** [Kimundi/owning-ref-rs#8]
This might be more of a question than an issue, but...

Suppose I'm writing a function from which I want to return a `Vec<OwningRef<_, &[u8]>>`. Some of these slices are `Box<[u8]>`, others are `Rc<[u8]>`, and some are perhaps `Ref<[u8]>`. So when the caller of the function drops that `Vec<OwningRef<_, &[u8]>>`, the `Box<[u8]>`s will be deallocated, the `Rc<[u8]>`s will have their refcount decreased, and the `Ref<[u8]>`s will have their read count decreased.

Is this possible using the `Erased` functionality? It seems like erasing a `OwningRef<Box<[u8]>, [u8]>` will give you a `OwningRef<Box<Erased>, [u8]>`, where I'm actually is looking for a `OwningRef<Erased, [u8]>` so I can abstract over several types of smart pointers.

**Comment by Kimundi** [comment]
Directly erasing the owner like this is not really doable with the memory layout of OwningRef, and looking at that ARef PR handling this by completely transmuting away the underlying type seems like a too error prone solution.

However, it should be possible to just add another layer of indirection, by creating a OwningRef of `Box<Box<[u8]>>`, `Box<Rc<[u8]>>`, `Box<Ref<[u8]>>`, etc. Those can all be erased to the common `Box<Erased>`.

**Comment by Kimundi** [comment]
I added some new methods for mapping the owner like this.

**Comment by diwic** [comment]
Oh, since I didn't get a reply in a timely fashion, I went ahead and created my own crate instead. [Here's my ARef](https://docs.rs/reffers/0.4.1/reffers/aref/struct.ARef.html).
